#!/usr/bin/env python3
"""Build useful static voice profiles from verified catalog facts, without invented biographies."""
import html
import json
import re
from datetime import date
from pathlib import Path
from urllib.parse import quote
from runpy import run_path

MARKER = '<!-- Generated by A Locução voice profile generator -->'
BASE = 'https://alocucao.com.br'
CATALOG = Path('assets/voices-catalog.json')
STYLE_COPY = {
 'Padrão': ('Locução padrão e institucional', 'Ouça a demonstração para avaliar uma interpretação clara e equilibrada para apresentações, mensagens de marca e vídeos institucionais.'),
 'Impacto': ('Locução de impacto', 'Compare a presença e a intensidade da interpretação para chamadas e mensagens que precisam destacar uma informação importante.'),
 'Animada': ('Locução animada', 'Observe a energia e o ritmo da voz para campanhas, ofertas e conteúdos que pedem uma interpretação mais entusiasmada.'),
 'Varejo': ('Locução para varejo e ofertas', 'Avalie como a voz comunica produtos, condições e preços em anúncios de lojas, supermercados e campanhas promocionais.'),
 'Caricata': ('Voz caricata e interpretação de personagem', 'Escute as possibilidades de interpretação e explique o personagem ou o tom desejado no pedido para alinhar a gravação.'),
 'Política': ('Locução para campanhas políticas', 'Para materiais de campanha, informe o formato, o roteiro e o tom de interpretação desejado. Confirme as condições do serviço no atendimento.'),
 'VSL': ('Locução para VSL e vídeos de vendas', 'Compare ritmo, pausas e clareza para vídeos de vendas. Informe a duração prevista e o objetivo do roteiro ao solicitar o orçamento.'),
 'Vídeo': ('Locução para vídeo', 'Avalie a relação entre a interpretação e as imagens do seu projeto. Envie o roteiro e as orientações de sincronização no atendimento.')
}

def esc(value): return html.escape(str(value),quote=True)
def jsonld(value): return json.dumps(value,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')
def display_name(name):
    words=name.title().split()
    return ' '.join(w.lower() if i and w.lower() in {'de','da','do','dos','das','e'} else w for i,w in enumerate(words))

def schedule_markup(voice):
    rows=voice.get('schedule',[])
    if not rows:return '<p>O perfil de origem não informou uma agenda de gravação válida. Confirme os horários no atendimento.</p>'
    return '<ul class="profile-hours">'+''.join('<li><strong>'+esc(d['day'])+'</strong><span>'+esc(' · '.join(i['start']+'–'+i['end'] for i in d['intervals']))+'</span></li>' for d in rows)+'</ul>'

def render(voice, voices):
    name=display_name(voice['name']);url=BASE+voice['localProfile']
    kind='voz '+voice['type'].lower() if voice.get('type') else 'voz profissional'
    profession='Locutora' if voice.get('type')=='Feminina' else 'Locutor' if voice.get('type')=='Masculina' else 'Profissional de locução'
    styles=voice.get('styles',[]);languages=voice.get('languages',[]);region=voice.get('region')
    desc=f'Ouça a demonstração de {name}, {kind}. '+('Estilos: '+', '.join(styles[:4])+'. ' if styles else '')+'Confira horários e solicite sua locução na A Locução.'
    title=f'{name}: {profession.lower()}, {kind}'+(' | '+region if region else '')+' | A Locução'
    initials=''.join(x[0] for x in name.split()[:2]);photo=voice.get('photo')
    portrait=('<img src="'+esc(photo)+'" alt="Foto de '+esc(name)+'" width="160" height="160" decoding="async">') if photo else '<span class="profile-initials" aria-hidden="true">'+esc(initials)+'</span>'
    whatsapp='https://wa.me/5527996529832?text='+quote(f'Olá! Ouvi a demonstração de {voice["name"]} na A Locução. Quero verificar disponibilidade e orçamento para meu projeto.')
    person={'@type':'Person','@id':url+'#locutor','name':voice['name'],'url':url,'jobTitle':profession,'knowsLanguage':languages}
    if photo:person['image']=BASE+photo
    schema={'@context':'https://schema.org','@type':'WebPage','@id':url+'#pagina','url':url,'name':title,'description':desc,'inLanguage':'pt-BR','mainEntity':person,'associatedMedia':{'@type':'AudioObject','name':'Demonstração de voz de '+name,'contentUrl':voice['audio'],'encodingFormat':'audio/mpeg','creator':{'@id':url+'#locutor'}}}
    breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Início','item':BASE+'/'},{'@type':'ListItem','position':2,'name':'Banco de vozes','item':BASE+'/vozes/'},{'@type':'ListItem','position':3,'name':name,'item':url}]}
    facts=('<div><dt>Perfil de voz</dt><dd>'+esc(kind.capitalize())+'</dd></div>')+('<div><dt>Região informada</dt><dd>'+esc(region)+'</dd></div>' if region else '')+('<div><dt>Idiomas no catálogo</dt><dd>'+esc(' · '.join(languages))+'</dd></div>' if languages else '')
    style_cards=''.join('<li><h3>'+esc(STYLE_COPY.get(s,(s,''))[0])+'</h3><p>'+esc(STYLE_COPY.get(s,(s,'Confira a interpretação na demonstração e alinhe o tom desejado no atendimento.'))[1])+'</p></li>' for s in styles)
    candidates=[v for v in voices if v['id']!=voice['id'] and v.get('type')==voice.get('type')]
    candidates.sort(key=lambda v:(-len(set(styles)&set(v.get('styles',[]))),v['name']))
    related=candidates[:3]
    related_html=''.join('<li><a href="'+esc(v['localProfile'])+'">'+esc(display_name(v['name']))+'</a><span>'+esc(', '.join(v.get('styles',[])[:3]) or 'Ouça a demonstração')+'</span></li>' for v in related)
    region_intro=f' A região informada no catálogo é {region}.' if region else ''
    prefix='na ' if region in {'Bahia','Paraíba'} else 'no ' if region in {'Acre','Amapá','Amazonas','Ceará','Distrito Federal','Espírito Santo','Maranhão','Mato Grosso','Mato Grosso do Sul','Pará','Paraná','Piauí','Rio de Janeiro','Rio Grande do Norte','Rio Grande do Sul','Tocantins'} else 'em '
    local_phrase=prefix+region if region else ''
    professional_label='uma locutora' if voice.get('type')=='Feminina' else 'um locutor' if voice.get('type')=='Masculina' else 'um profissional de locução'
    regional = ('<section class="profile-panel"><h2>Como escolher '+professional_label+' '+esc(local_phrase)+'</h2><p>'+esc(region)+' é a região informada para '+esc(name)+' no catálogo. Se você busca uma voz para uma campanha nessa região, compare a demonstração com o público e a mensagem do seu projeto. O pedido pode ser orientado online pelo WhatsApp da A Locução.</p><p>Informe se precisa de pronúncias locais ou de uma interpretação específica. A região cadastrada ajuda na escolha, mas o sotaque e o resultado desejado devem ser avaliados pela demo e alinhados no atendimento.</p></section>') if region else ''
    choose_label='Escolher esta locutora' if voice.get('type')=='Feminina' else 'Escolher este locutor' if voice.get('type')=='Masculina' else 'Escolher esta voz'
    return f'''<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
{MARKER}
<title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{esc(url)}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta name="theme-color" content="#0b1726">
<meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:url" content="{esc(url)}">{('<meta property="og:image" content="'+esc(BASE+photo)+'">') if photo else ''}
<link rel="stylesheet" href="/assets/voice-bank.css?v=20261001-hours"><link rel="stylesheet" href="/assets/voice-profile.css?v=20261001"><script src="/assets/privacy.js?v=20261001" defer></script><script src="/assets/tracking.js" defer></script>
<script type="application/ld+json">{jsonld(schema)}</script><script type="application/ld+json">{jsonld(breadcrumb)}</script></head>
<body data-voice-id="{esc(voice['id'])}"><a class="skip-link" href="#demo">Ir para a demonstração de voz</a><header><div class="container"><nav aria-label="Navegação principal"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">∿</span>A Locução</a><button class="mobile-toggle" aria-label="Abrir menu" aria-expanded="false" aria-controls="main-menu">☰</button><div class="menu" id="main-menu"><a href="/vozes/#voice-grid">Banco de vozes</a><a href="/servicos/">Serviços</a><a href="/precos/">Preços</a><a class="nav-cta" href="{esc(whatsapp)}" target="_blank" rel="noopener" data-cta="perfil_topo">Verificar orçamento ↗</a></div></nav></div></header>
<main><section class="profile-hero"><div class="container"><nav class="profile-breadcrumb" aria-label="Navegação estrutural"><a href="/">Início</a><span aria-hidden="true">/</span><a href="/vozes/">Banco de vozes</a><span aria-hidden="true">/</span><span aria-current="page">{esc(name)}</span></nav><div class="profile-heading"><div><p class="eyebrow">VOZ HUMANA. INTERPRETAÇÃO PARA SUA MENSAGEM.</p><h1>{esc(name)}<em>{esc(kind.capitalize())} para locução</em></h1>{('<p class="profile-region">Região informada: '+esc(region)+'</p>') if region else ''}<p class="profile-lead">Ouça a demonstração de voz de {esc(name)} e conheça os estilos informados no catálogo: {esc(', '.join(styles)) if styles else 'consulte as opções no atendimento'}. Compare a interpretação com o que seu projeto precisa.</p></div><div class="profile-portrait">{portrait}</div></div></div></section>
<section class="profile-main"><div class="container profile-columns"><div class="profile-content"><section class="profile-panel" id="demo" aria-labelledby="demo-title"><p class="eyebrow dark-eyebrow">ESCUTE ANTES DE ESCOLHER</p><h2 id="demo-title">Demonstração de voz de {esc(name)}</h2><p>Ouça a amostra de locução para avaliar o timbre, a dicção, o ritmo e a interpretação. A demo apresenta o trabalho da voz; o tom da sua gravação será alinhado a partir do roteiro.</p><audio id="profile-audio" aria-label="Demonstração de voz de {esc(name)}" controls preload="none" src="{esc(voice['audio'])}" data-voice="{esc(voice['name'])}"><a href="{esc(voice['audio'])}">Ouvir demonstração de {esc(name)}</a></audio><p id="profile-audio-error" hidden>A demonstração não pôde ser reproduzida. Tente novamente ou peça orientação no atendimento.</p><div class="profile-status"><span id="profile-status">Consulte a disponibilidade no atendimento</span><span id="profile-sync"></span></div><noscript><p>Você pode ouvir a demo e enviar seu pedido. O status atualizado depende de JavaScript; confirme disponibilidade e prazo no atendimento.</p></noscript></section>
<section class="profile-panel"><h2>Conheça o perfil de {esc(name)}</h2><p>{esc(name)} está no banco de vozes da A Locução com o perfil de {esc(kind)}.{esc(region_intro)} Use as informações abaixo junto com a demonstração para comparar opções antes de contratar.</p><dl class="profile-facts">{facts}</dl></section>{regional}
<section class="profile-panel"><h2>Estilos de locução de {esc(name)}</h2><ul class="profile-styles">{style_cards if style_cards else '<li><p>Os estilos não foram informados. Explique sua necessidade no atendimento.</p></li>'}</ul><p class="profile-note">Os estilos acima são informados no catálogo. Para uma interpretação específica, envie referências e orientações junto com o texto.</p></section>
<section class="profile-panel" aria-labelledby="hours-title"><h2 id="hours-title">Horários de gravação</h2><div id="profile-schedule">{schedule_markup(voice)}</div><p class="profile-note">Agenda informada pelo perfil de origem. Os dias ausentes não indicam folga. Confirme o fuso, a disponibilidade e o prazo no atendimento.</p></section>
<section class="profile-panel"><h2>Como pedir uma locução com {esc(name)}</h2><ol class="profile-request"><li>Envie o roteiro e diga onde a gravação será usada: comercial, vídeo, vinheta ou atendimento telefônico.</li><li>Informe o estilo de interpretação e o prazo desejados.</li><li>Confirme o orçamento e a disponibilidade pelo atendimento da A Locução.</li></ol><p>Precisa apenas da gravação da voz? Veja <a href="/locucao-off/">locução off</a>. Para áudio produzido com voz, trilha e efeitos conforme o serviço, conheça <a href="/spot-comercial/">spot comercial</a>. Consulte também <a href="/precos/">os preços</a> e a <a href="/calculadora/">calculadora de tempo do roteiro</a>.</p></section>
<section class="profile-panel"><h2>Outras vozes para comparar</h2><p>Conheça profissionais do mesmo perfil de voz, priorizando estilos em comum.</p><ul class="profile-related">{related_html}</ul><a class="profile-back" href="/vozes/#voice-grid">← Voltar a todas as demonstrações de voz</a></section></div>
<aside class="profile-contact"><div class="profile-panel"><p class="eyebrow dark-eyebrow">SUA PRÓXIMA GRAVAÇÃO</p><h2>Gostou desta voz?</h2><p>Envie o texto e conte como será usado. A equipe confirma o serviço, a disponibilidade e o prazo.</p><a class="btn-wa" href="{esc(whatsapp)}" target="_blank" rel="noopener" data-cta="perfil_escolher">{esc(choose_label)} ↗</a><a class="profile-back" href="/vozes/#voice-grid">Comparar outras vozes</a></div></aside></div></section></main>
<footer><div class="container foot"><a class="brand" href="/">A Locução</a><span>Vozes humanas. Mensagens que conectam.</span><div><a href="/vozes/">Banco de vozes</a><a href="/servicos/">Serviços</a><a href="/politica-de-privacidade/">Privacidade</a></div></div></footer><script src="/assets/site.js"></script><script src="/assets/voice-profile.js?v=20261001" defer></script></body></html>'''

def main():
    catalog=json.loads(CATALOG.read_text(encoding='utf-8'));voices=catalog['voices'];generated=0;changed=set()
    for voice in voices:
        path=voice.get('localProfile','')
        if not re.fullmatch(r'/perfil-locutor-[a-z0-9][a-z0-9-]*/',path):raise ValueError('Invalid profile route')
        dest=Path(path.strip('/'))/'index.html';existing=dest.read_text(encoding='utf-8') if dest.exists() else None
        if existing is None or MARKER in existing:
            output=run_path('scripts/standardize-layout.py')['standardize_page'](render(voice,voices))+'\n';dest.parent.mkdir(parents=True,exist_ok=True)
            if output!=existing:
                dest.write_text(output,encoding='utf-8');changed.add(BASE+voice['localProfile'])
            generated+=1
        voice['profilePublished']=dest.is_file()
    CATALOG.write_text(json.dumps(catalog,ensure_ascii=False,separators=(',',':'))+'\n',encoding='utf-8')
    Path('data/voice-profile-routes.json').write_text(json.dumps([{'id':v['id'],'name':v['name'],'path':v['localProfile'],'url':BASE+v['localProfile'],'published':v['profilePublished']} for v in voices],ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    run_path('scripts/sync-voices.py')['update_schema'](voices)
    sitemap=Path('sitemap.xml');xml=sitemap.read_text(encoding='utf-8')
    existing_dates=dict(re.findall(r'<url>\s*<loc>(https://alocucao\.com\.br/perfil-locutor-[^<]+)</loc>\s*<lastmod>([^<]+)</lastmod>',xml))
    block='<!-- voice-profiles:start -->\n'+''.join('  <url><loc>'+BASE+v['localProfile']+'</loc><lastmod>'+(date.today().isoformat() if BASE+v['localProfile'] in changed else existing_dates.get(BASE+v['localProfile'],date.today().isoformat()))+'</lastmod></url>\n' for v in voices if v['profilePublished'])+'<!-- voice-profiles:end -->'
    if '<!-- voice-profiles:start -->' in xml:xml=re.sub(r'<!-- voice-profiles:start -->.*?<!-- voice-profiles:end -->',lambda _:block,xml,flags=re.S)
    else:xml=xml.replace('</urlset>',block+'\n</urlset>')
    sitemap.write_text(xml,encoding='utf-8')
    print(f'Profile pages ready: {sum(v["profilePublished"] for v in voices)}/{len(voices)}; managed profiles: {generated}')

if __name__=='__main__':main()
